/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ASkeleton: typeof import('ant-design-vue/es')['Skeleton']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    UsersTable: typeof import('./src/components/UsersTable.vue')['default']
  }
}
